package entity;
// Generated Feb 17, 2017 4:46:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer eventId;
     private String eventName;
     private String eventPlace;
     private Date startDate;
     private Date endDate;
     private long oneDayTicketPrice;
     private long allDaysTicketPrice;
     private short maxReservationsPerUser;
     private int maxTicketsAvailablePerDay;
     private int viewCount;
     private int sellCount;
     private boolean cancelled;
     private float rating;
     private Set ticketsRemainings = new HashSet(0);
     private Set videos = new HashSet(0);
     private Set reservations = new HashSet(0);
     private Set images = new HashSet(0);
     private Set performers = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set socialLinks = new HashSet(0);

    public Event() {
    }

	
    public Event(String eventName, String eventPlace, Date startDate, Date endDate, long oneDayTicketPrice, long allDaysTicketPrice, short maxReservationsPerUser, int maxTicketsAvailablePerDay, int viewCount, int sellCount, boolean cancelled, float rating) {
        this.eventName = eventName;
        this.eventPlace = eventPlace;
        this.startDate = startDate;
        this.endDate = endDate;
        this.oneDayTicketPrice = oneDayTicketPrice;
        this.allDaysTicketPrice = allDaysTicketPrice;
        this.maxReservationsPerUser = maxReservationsPerUser;
        this.maxTicketsAvailablePerDay = maxTicketsAvailablePerDay;
        this.viewCount = viewCount;
        this.sellCount = sellCount;
        this.cancelled = cancelled;
        this.rating = rating;
    }
    public Event(String eventName, String eventPlace, Date startDate, Date endDate, long oneDayTicketPrice, long allDaysTicketPrice, short maxReservationsPerUser, int maxTicketsAvailablePerDay, int viewCount, int sellCount, boolean cancelled, float rating, Set ticketsRemainings, Set videos, Set reservations, Set images, Set performers, Set messages, Set socialLinks) {
       this.eventName = eventName;
       this.eventPlace = eventPlace;
       this.startDate = startDate;
       this.endDate = endDate;
       this.oneDayTicketPrice = oneDayTicketPrice;
       this.allDaysTicketPrice = allDaysTicketPrice;
       this.maxReservationsPerUser = maxReservationsPerUser;
       this.maxTicketsAvailablePerDay = maxTicketsAvailablePerDay;
       this.viewCount = viewCount;
       this.sellCount = sellCount;
       this.cancelled = cancelled;
       this.rating = rating;
       this.ticketsRemainings = ticketsRemainings;
       this.videos = videos;
       this.reservations = reservations;
       this.images = images;
       this.performers = performers;
       this.messages = messages;
       this.socialLinks = socialLinks;
    }
   
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getEventPlace() {
        return this.eventPlace;
    }
    
    public void setEventPlace(String eventPlace) {
        this.eventPlace = eventPlace;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public long getOneDayTicketPrice() {
        return this.oneDayTicketPrice;
    }
    
    public void setOneDayTicketPrice(long oneDayTicketPrice) {
        this.oneDayTicketPrice = oneDayTicketPrice;
    }
    public long getAllDaysTicketPrice() {
        return this.allDaysTicketPrice;
    }
    
    public void setAllDaysTicketPrice(long allDaysTicketPrice) {
        this.allDaysTicketPrice = allDaysTicketPrice;
    }
    public short getMaxReservationsPerUser() {
        return this.maxReservationsPerUser;
    }
    
    public void setMaxReservationsPerUser(short maxReservationsPerUser) {
        this.maxReservationsPerUser = maxReservationsPerUser;
    }
    public int getMaxTicketsAvailablePerDay() {
        return this.maxTicketsAvailablePerDay;
    }
    
    public void setMaxTicketsAvailablePerDay(int maxTicketsAvailablePerDay) {
        this.maxTicketsAvailablePerDay = maxTicketsAvailablePerDay;
    }
    public int getViewCount() {
        return this.viewCount;
    }
    
    public void setViewCount(int viewCount) {
        this.viewCount = viewCount;
    }
    public int getSellCount() {
        return this.sellCount;
    }
    
    public void setSellCount(int sellCount) {
        this.sellCount = sellCount;
    }
    public boolean isCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(boolean cancelled) {
        this.cancelled = cancelled;
    }
    public float getRating() {
        return this.rating;
    }
    
    public void setRating(float rating) {
        this.rating = rating;
    }
    public Set getTicketsRemainings() {
        return this.ticketsRemainings;
    }
    
    public void setTicketsRemainings(Set ticketsRemainings) {
        this.ticketsRemainings = ticketsRemainings;
    }
    public Set getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set videos) {
        this.videos = videos;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }
    public Set getImages() {
        return this.images;
    }
    
    public void setImages(Set images) {
        this.images = images;
    }
    public Set getPerformers() {
        return this.performers;
    }
    
    public void setPerformers(Set performers) {
        this.performers = performers;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }
    public Set getSocialLinks() {
        return this.socialLinks;
    }
    
    public void setSocialLinks(Set socialLinks) {
        this.socialLinks = socialLinks;
    }




}


