package entity;
// Generated Feb 17, 2017 4:46:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Performer generated by hbm2java
 */
public class Performer  implements java.io.Serializable {


     private Integer performerId;
     private Event event;
     private String performerName;
     private Date startTime;
     private Date endTime;

    public Performer() {
    }

    public Performer(Event event, String performerName, Date startTime, Date endTime) {
       this.event = event;
       this.performerName = performerName;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public Integer getPerformerId() {
        return this.performerId;
    }
    
    public void setPerformerId(Integer performerId) {
        this.performerId = performerId;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public String getPerformerName() {
        return this.performerName;
    }
    
    public void setPerformerName(String performerName) {
        this.performerName = performerName;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


