package entity;
// Generated Feb 17, 2017 4:46:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer reservationId;
     private Event event;
     private User user;
     private String status;
     private Date reservationDatetime;
     private String type;
     private boolean cancelledEvent;
     private Integer daySelected;

    public Reservation() {
    }

	
    public Reservation(Event event, User user, String status, Date reservationDatetime, String type, boolean cancelledEvent) {
        this.event = event;
        this.user = user;
        this.status = status;
        this.reservationDatetime = reservationDatetime;
        this.type = type;
        this.cancelledEvent = cancelledEvent;
    }
    public Reservation(Event event, User user, String status, Date reservationDatetime, String type, boolean cancelledEvent, Integer daySelected) {
       this.event = event;
       this.user = user;
       this.status = status;
       this.reservationDatetime = reservationDatetime;
       this.type = type;
       this.cancelledEvent = cancelledEvent;
       this.daySelected = daySelected;
    }
   
    public Integer getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getReservationDatetime() {
        return this.reservationDatetime;
    }
    
    public void setReservationDatetime(Date reservationDatetime) {
        this.reservationDatetime = reservationDatetime;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public boolean isCancelledEvent() {
        return this.cancelledEvent;
    }
    
    public void setCancelledEvent(boolean cancelledEvent) {
        this.cancelledEvent = cancelledEvent;
    }
    public Integer getDaySelected() {
        return this.daySelected;
    }
    
    public void setDaySelected(Integer daySelected) {
        this.daySelected = daySelected;
    }
}


