package entity;
// Generated Feb 17, 2017 4:46:51 PM by Hibernate Tools 4.3.1



/**
 * SocialLink generated by hbm2java
 */
public class SocialLink  implements java.io.Serializable {


     private Integer socialLinkId;
     private Event event;
     private String networkName;
     private String url;

    public SocialLink() {
    }

    public SocialLink(Event event, String networkName, String url) {
       this.event = event;
       this.networkName = networkName;
       this.url = url;
    }
   
    public Integer getSocialLinkId() {
        return this.socialLinkId;
    }
    
    public void setSocialLinkId(Integer socialLinkId) {
        this.socialLinkId = socialLinkId;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public String getNetworkName() {
        return this.networkName;
    }
    
    public void setNetworkName(String networkName) {
        this.networkName = networkName;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


