package entity;
// Generated Feb 17, 2017 4:46:51 PM by Hibernate Tools 4.3.1



/**
 * TicketsRemaining generated by hbm2java
 */
public class TicketsRemaining  implements java.io.Serializable {


     private TicketsRemainingId id;
     private Event event;
     private int available;

    public TicketsRemaining() {
    }

    public TicketsRemaining(TicketsRemainingId id, Event event, int available) {
       this.id = id;
       this.event = event;
       this.available = available;
    }
   
    public TicketsRemainingId getId() {
        return this.id;
    }
    
    public void setId(TicketsRemainingId id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public int getAvailable() {
        return this.available;
    }
    
    public void setAvailable(int available) {
        this.available = available;
    }




}


