package entity;
// Generated Feb 17, 2017 4:46:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String firstName;
     private String lastName;
     private String username;
     private String password;
     private String phone;
     private String EMail;
     private String status;
     private Date lastLoginTime;
     private String fbId;
     private String GId;
     private boolean admin;
     private byte failedReservations;
     private Set reservations = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set userReviews = new HashSet(0);

    public User() {
    }

	
    public User(boolean admin, byte failedReservations) {
        this.admin = admin;
        this.failedReservations = failedReservations;
    }
    public User(String firstName, String lastName, String username, String password, String phone, String EMail, String status, Date lastLoginTime, String fbId, String GId, boolean admin, byte failedReservations, Set reservations, Set messages, Set userReviews) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.username = username;
       this.password = password;
       this.phone = phone;
       this.EMail = EMail;
       this.status = status;
       this.lastLoginTime = lastLoginTime;
       this.fbId = fbId;
       this.GId = GId;
       this.admin = admin;
       this.failedReservations = failedReservations;
       this.reservations = reservations;
       this.messages = messages;
       this.userReviews = userReviews;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }
    
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
    public String getFbId() {
        return this.fbId;
    }
    
    public void setFbId(String fbId) {
        this.fbId = fbId;
    }
    public String getGId() {
        return this.GId;
    }
    
    public void setGId(String GId) {
        this.GId = GId;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public byte getFailedReservations() {
        return this.failedReservations;
    }
    
    public void setFailedReservations(byte failedReservations) {
        this.failedReservations = failedReservations;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }
    public Set getUserReviews() {
        return this.userReviews;
    }
    
    public void setUserReviews(Set userReviews) {
        this.userReviews = userReviews;
    }




}


