package entity;
// Generated Feb 17, 2017 4:46:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserReview generated by hbm2java
 */
public class UserReview  implements java.io.Serializable {


     private Integer reviewId;
     private User user;
     private String eventName;
     private String comment;
     private Byte rating;
     private Date reviewTime;

    public UserReview() {
    }

	
    public UserReview(User user, String eventName) {
        this.user = user;
        this.eventName = eventName;
    }
    public UserReview(User user, String eventName, String comment, Byte rating, Date reviewTime) {
       this.user = user;
       this.eventName = eventName;
       this.comment = comment;
       this.rating = rating;
       this.reviewTime = reviewTime;
    }
   
    public Integer getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Byte getRating() {
        return this.rating;
    }
    
    public void setRating(Byte rating) {
        this.rating = rating;
    }
    public Date getReviewTime() {
        return this.reviewTime;
    }
    
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }




}


