package entity;
// Generated Feb 17, 2017 4:46:51 PM by Hibernate Tools 4.3.1



/**
 * Video generated by hbm2java
 */
public class Video  implements java.io.Serializable {


     private Integer videoId;
     private Event event;
     private String videoUrl;
     private boolean approved;

    public Video() {
    }

    public Video(Event event, String videoUrl, boolean approved) {
       this.event = event;
       this.videoUrl = videoUrl;
       this.approved = approved;
    }
   
    public Integer getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public String getVideoUrl() {
        return this.videoUrl;
    }
    
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }
    public boolean isApproved() {
        return this.approved;
    }
    
    public void setApproved(boolean approved) {
        this.approved = approved;
    }




}


